export const colors = {
  screen: '#0B1D3A',
  surface: '#1E3F6F',
  surfaceElevated: '#16325F',
  surfaceMuted: '#13284D',
  surfaceInset: '#1A2F57',
  border: '#2A5088',
  borderSubtle: '#1A2F57',
  accent: '#3D7BFF',
  accentSoft: '#7EC8FF',
  accentMuted: '#5B9BFF',
  textPrimary: '#FFFFFF',
  textSecondary: '#C7D7F2',
  textMuted: '#9BB4DE',
  textHint: '#7A95C4',
  textOnAccent: '#FFFFFF',
  warning: '#FFD27A',
  errorSurface: '#1A2F57',
  errorText: '#FFD1D1',
  chartLine: '#5B9BFF',
  chartHighlight: '#FFEB3B',
  chartMarker: '#FFFFFF',
  scrubberTrack: '#3D7BFF',
  scrubberProgress: '#FFFFFF',
  scrubberThumb: '#F2FAFF',
  overlay: 'rgba(0,0,0,0.55)',
  // Legacy aliases used across tiles
  tile: '#1E3F6F',
  tileBorder: '#2A5088',
  card: '#162E52',
  cardElevated: '#13284D',
} as const;

export type AppColor = (typeof colors)[keyof typeof colors];
